"""HTML report export for scan findings and removal request data."""

from __future__ import annotations
import html
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from src.config import DATA_DIR
from src.db import Database

logger = logging.getLogger(__name__)

# Dark theme matching the web UI aesthetic
_CSS = """\
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    background: #0f1117;
    color: #e0e0e0;
    padding: 2rem;
    line-height: 1.6;
}
.container { max-width: 1100px; margin: 0 auto; }
h1 {
    color: #60a5fa;
    font-size: 1.8rem;
    margin-bottom: 0.25rem;
}
.subtitle {
    color: #9ca3af;
    font-size: 0.95rem;
    margin-bottom: 2rem;
}
.summary {
    display: flex;
    gap: 1.5rem;
    margin-bottom: 2rem;
    flex-wrap: wrap;
}
.stat-card {
    background: #1e2130;
    border: 1px solid #2d3148;
    border-radius: 8px;
    padding: 1rem 1.5rem;
    min-width: 140px;
}
.stat-card .label { color: #9ca3af; font-size: 0.85rem; }
.stat-card .value { color: #f0f0f0; font-size: 1.6rem; font-weight: 700; }
table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 1rem;
    background: #1e2130;
    border-radius: 8px;
    overflow: hidden;
}
thead th {
    background: #262a3d;
    color: #9ca3af;
    text-transform: uppercase;
    font-size: 0.75rem;
    letter-spacing: 0.05em;
    padding: 0.75rem 1rem;
    text-align: left;
    border-bottom: 1px solid #2d3148;
}
tbody td {
    padding: 0.65rem 1rem;
    border-bottom: 1px solid #2d3148;
    font-size: 0.9rem;
    vertical-align: top;
}
tbody tr:last-child td { border-bottom: none; }
tbody tr:hover { background: #262a3d; }
.confidence-high { color: #ef4444; font-weight: 600; }
.confidence-medium { color: #f59e0b; }
.confidence-low { color: #6b7280; }
.status-pending { color: #f59e0b; }
.status-submitted { color: #3b82f6; }
.status-confirmed { color: #22c55e; }
.status-rejected { color: #ef4444; }
.status-reappeared { color: #ef4444; font-weight: 600; }
a { color: #60a5fa; text-decoration: none; }
a:hover { text-decoration: underline; }
.empty-msg {
    text-align: center;
    padding: 3rem;
    color: #6b7280;
    font-style: italic;
}
.footer {
    margin-top: 2rem;
    padding-top: 1rem;
    border-top: 1px solid #2d3148;
    color: #6b7280;
    font-size: 0.8rem;
}
"""


def _esc(value: str) -> str:
    """HTML-escape a string."""
    return html.escape(str(value)) if value else ""


def _confidence_class(confidence: str) -> str:
    return f"confidence-{confidence}" if confidence in ("high", "medium", "low") else ""


def _status_class(status: str) -> str:
    return f"status-{status}" if status in ("pending", "submitted", "confirmed", "rejected", "reappeared") else ""


def _build_page(title: str, body_content: str) -> str:
    """Wrap body content in a full HTML document."""
    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_esc(title)}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="container">
{body_content}
<div class="footer">
    Generated by Privacy Toolkit on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
</div>
</div>
</body>
</html>"""


def export_findings_html(
    findings: list[dict],
    output_path: Optional[str] = None,
    profile_name: str = "",
) -> str:
    """Export findings to an HTML report file.

    Args:
        findings: List of finding dicts from Database.get_findings().
        output_path: Destination file path. Auto-generated if not provided.
        profile_name: Profile name for the report title.

    Returns:
        The path the HTML file was written to.
    """
    if output_path:
        path = Path(output_path)
    else:
        path = DATA_DIR / "scans" / f"findings_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    path.parent.mkdir(parents=True, exist_ok=True)

    logger.info("Exporting %d findings to HTML: %s", len(findings), path)

    title = "Privacy Toolkit — Findings Report"
    if profile_name:
        title += f" for {profile_name}"

    # Summary stats
    sources = set()
    sites = set()
    confidence_counts: dict[str, int] = {}
    for f in findings:
        sources.add(f.get("source", ""))
        sites.add(f.get("site_name", ""))
        conf = f.get("confidence", "medium")
        confidence_counts[conf] = confidence_counts.get(conf, 0) + 1

    summary_cards = f"""\
<div class="summary">
    <div class="stat-card"><div class="label">Total Findings</div><div class="value">{len(findings)}</div></div>
    <div class="stat-card"><div class="label">Unique Sites</div><div class="value">{len(sites)}</div></div>
    <div class="stat-card"><div class="label">Scanners Used</div><div class="value">{len(sources)}</div></div>
    <div class="stat-card"><div class="label">High Confidence</div><div class="value">{confidence_counts.get("high", 0)}</div></div>
</div>"""

    # Table
    if findings:
        rows = []
        for f in findings:
            details = f.get("details", {})
            if isinstance(details, str):
                try:
                    details = json.loads(details)
                except (json.JSONDecodeError, TypeError):
                    pass
            details_str = json.dumps(details, default=str) if isinstance(details, dict) else str(details)
            # Truncate long details for display
            if len(details_str) > 120:
                details_str = details_str[:120] + "..."

            conf = f.get("confidence", "medium")
            url = f.get("site_url", "")
            url_cell = f'<a href="{_esc(url)}" target="_blank">{_esc(url)}</a>' if url else ""

            rows.append(f"""\
<tr>
    <td>{_esc((f.get("found_at") or "")[:10])}</td>
    <td>{_esc(f.get("source", ""))}</td>
    <td>{_esc(f.get("site_name", ""))}</td>
    <td>{url_cell}</td>
    <td>{_esc(f.get("data_type", ""))}</td>
    <td class="{_confidence_class(conf)}">{_esc(conf)}</td>
    <td>{_esc(details_str)}</td>
</tr>""")

        table_html = f"""\
<table>
<thead>
<tr>
    <th>Date</th>
    <th>Scanner</th>
    <th>Site</th>
    <th>URL</th>
    <th>Data Type</th>
    <th>Confidence</th>
    <th>Details</th>
</tr>
</thead>
<tbody>
{"".join(rows)}
</tbody>
</table>"""
    else:
        table_html = '<div class="empty-msg">No findings to display.</div>'

    body = f"""\
<h1>{_esc(title)}</h1>
<div class="subtitle">Generated {datetime.now().strftime('%B %d, %Y at %H:%M')}</div>
{summary_cards}
{table_html}"""

    page = _build_page(title, body)
    path.write_text(page, encoding="utf-8")

    logger.info("HTML export complete: %s (%d findings)", path, len(findings))
    return str(path)


def export_removals_html(
    removals: list[dict],
    output_path: Optional[str] = None,
    profile_name: str = "",
) -> str:
    """Export removal requests to an HTML report file.

    Args:
        removals: List of removal dicts from Database.get_removals().
        output_path: Destination file path. Auto-generated if not provided.
        profile_name: Profile name for the report title.

    Returns:
        The path the HTML file was written to.
    """
    if output_path:
        path = Path(output_path)
    else:
        path = DATA_DIR / "scans" / f"removals_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    path.parent.mkdir(parents=True, exist_ok=True)

    logger.info("Exporting %d removals to HTML: %s", len(removals), path)

    title = "Privacy Toolkit — Removal Status Report"
    if profile_name:
        title += f" for {profile_name}"

    # Summary stats
    status_counts: dict[str, int] = {}
    for r in removals:
        st = r.get("status", "unknown")
        status_counts[st] = status_counts.get(st, 0) + 1

    summary_cards = f"""\
<div class="summary">
    <div class="stat-card"><div class="label">Total Requests</div><div class="value">{len(removals)}</div></div>
    <div class="stat-card"><div class="label">Confirmed</div><div class="value">{status_counts.get("confirmed", 0)}</div></div>
    <div class="stat-card"><div class="label">Pending</div><div class="value">{status_counts.get("pending", 0)}</div></div>
    <div class="stat-card"><div class="label">Submitted</div><div class="value">{status_counts.get("submitted", 0)}</div></div>
</div>"""

    # Table
    if removals:
        rows = []
        for r in removals:
            status = r.get("status", "")
            rows.append(f"""\
<tr>
    <td>{_esc(r.get("broker_name", ""))}</td>
    <td>{_esc(r.get("method", ""))}</td>
    <td class="{_status_class(status)}">{_esc(status)}</td>
    <td>{_esc((r.get("submitted_at") or "")[:10])}</td>
    <td>{_esc((r.get("confirmed_at") or "")[:10])}</td>
    <td>{_esc(r.get("notes", "") or "")}</td>
</tr>""")

        table_html = f"""\
<table>
<thead>
<tr>
    <th>Broker</th>
    <th>Method</th>
    <th>Status</th>
    <th>Submitted</th>
    <th>Confirmed</th>
    <th>Notes</th>
</tr>
</thead>
<tbody>
{"".join(rows)}
</tbody>
</table>"""
    else:
        table_html = '<div class="empty-msg">No removal requests to display.</div>'

    body = f"""\
<h1>{_esc(title)}</h1>
<div class="subtitle">Generated {datetime.now().strftime('%B %d, %Y at %H:%M')}</div>
{summary_cards}
{table_html}"""

    page = _build_page(title, body)
    path.write_text(page, encoding="utf-8")

    logger.info("HTML export complete: %s (%d removals)", path, len(removals))
    return str(path)


def export_findings(db: Database, profile: Optional[str] = None, output: Optional[str] = None) -> str:
    """High-level export: query findings from DB and write HTML.

    Mirrors the interface of json_export.export_findings for CLI integration.
    """
    findings = db.get_findings(profile=profile)
    return export_findings_html(findings, output, profile_name=profile or "")


def export_removals(db: Database, profile: Optional[str] = None, output: Optional[str] = None) -> str:
    """High-level export: query removals from DB and write HTML.

    Mirrors the interface of json_export.export_removals for CLI integration.
    """
    removals = db.get_removals(profile=profile)
    return export_removals_html(removals, output, profile_name=profile or "")
